name: Build Dylib

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 1. 下载代码
        uses: actions/checkout@v4

      - name: 2. 安装环境
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz -o ~/theos/sdks/iPhoneOS14.5.sdk.tar.xz
          tar -xf ~/theos/sdks/iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks/
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: 3. 检查文件位置
        run: |
          ls -R
          echo "THEOS 变量是: $THEOS"

      - name: 4. 强制编译
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1
